version: '3'
services:
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - server_mswt

  server:
    image: sv1net/mswt-server_prod
    env_file:
     - .env
    ports:
      - 3005:3005
    depends_on:
      - mongo
    networks:
      - server_mswt
    volumes:
      - uploads:/uploads
      - /root/application/mswt-server/.env:/usr/src/app/.env

  client:
    image: sv1net/mswt-client_prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    networks:
      - server_mswt
    volumes:
      - /etc/nginx/ssl/ru:/etc/nginx/ssl/ru  # Mount the SSL certificates volume
      - /etc/nginx/ssl/com:/etc/nginx/ssl/com  # Mount the SSL certificates volume
      - /root/application/my-simple-workout-tracker/.env.local:/bin/www/dist/.env.local

networks:
  server_mswt:
    driver: bridge

volumes:
  uploads:
