version: '3'
services:
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - server_mswt

  server:
    image: mswt-server_prod
    env_file:
     - .env
    ports:
      - 3005:3005
    depends_on:
      - mongo
    networks:
      - server_mswt
    volumes:
      - uploads:/uploads

  client:
    image: mswt-client_prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    networks:
      - server_mswt
    volumes:
      - ssl_certs:/etc/nginx/ssl  # Mount the SSL certificates volume

networks:
  server_mswt:
    driver: bridge

volumes:
  uploads:
  ssl_certs:
