version: "3"
services:
  mswt-server:
    image: mswt-server-dev
    ports:
      - "3005:3005"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --bind_ip 127.0.0.1,172.19.0.1
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
